import type { Metadata } from "next";
import "./globals.css";
import Provider from "./providers";
import { Navbar } from "../components/Navbar/navbar";
import Footer from "@/src/components/footer/Footer"
import Sidebar from "../components/sideBar/Sidebar";
import { SessionProvider } from "next-auth/react";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode,
  modal: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <Provider>
          <Navbar />
          <div className="d-flex">

            <div className="sidebar-layout sticky-top">
              <Sidebar />
            </div>

            <div className="body-child w-100">
              {children}
              <Footer />
            </div>

          </div>
          {modal}
          
        </Provider>
      </body>
    </html>
  );
}
